### ISSUE TITLE
Refactor JSON construction to use built in json library

### ISSUE THREAD

**Issue by AlecGoncharow** [BridgesUNCC/bridges-python#26]
Not critical, more of a QOL/Readability/Refractor-ability issue.

I needed to use the json library to escape strings from assignment titles, so I went ahead and converted that entire instance of JSON creation to using json.dumps():
```python
        ds = {
            "visual": self.vis_type,
            "title": self.title,
            "description": self.description,
            "coord_system_type": self.coord_system_type,
            "map_overlay": self.map_overlay,
        }
        ds_json = json.dumps(ds)[:-1] + ", "
```
which does the same work as 
```python
 ds_json = self.OPEN_CURLY + self.QUOTE + "visual" + self.QUOTE + self.COLON + self.QUOTE + self.vis_type + self.QUOTE + self.COMMA + self.QUOTE + "title" + self.QUOTE + self.COLON + self.QUOTE + self.title + self.QUOTE + self.COMMA + self.QUOTE + "description" + self.QUOTE + self.COLON + self.QUOTE + self.description + self.QUOTE + self.COMMA + self.QUOTE + "coord_system_type" + self.QUOTE + self.COLON + self.QUOTE + self.coord_system_type + self.QUOTE + self.COMMA + self.QUOTE + "map_overlay" + self.QUOTE + self.COLON + str(self.map_overlay).lower() + self.COMMA
```
I think this a lot more readable and handles the problems in escaping bad strings and the like. For now it is slicing off the end and adding a comma for compatibility with the rest of the JSON creation process, but I would imagine we could refactor to use it for all the data structures.

**Comment by krs-world** [comment]
Wow! Cool! Yeah, much better!

**Comment by esaule** [comment]
Indeed, we could improve readability of JSON formation in multiple
instances in the different clients.
