### ISSUE TITLE
Add symbol and symbol collection to exports in __init__.py

### ISSUE THREAD

**Issue by AlecGoncharow** [BridgesUNCC/bridges-python#59]
https://github.com/BridgesUNCC/bridges-python/blob/master/bridges/__init__.py

**Comment by esaule** [comment]
@AlecGoncharow I don't understand what that means. Also, is it critical as in need to be fixed right now?

**Comment by AlecGoncharow** [comment]
Basically as it stands all other data structures are imported by default with the `import bridges`

meaning:
```python
import bridges

my_color = Color('red')
my_array = Array()
"""
...etc are bridges data structures
"""
```
This is not the case with the symbol collection stuff.
I am not sure why, but it would make sense to be consistent.
