### ISSUE TITLE
bst_eq test is failing..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridges-python#77]
The time setter for the Eq data is not working. Not sure if I messed something durin the documentation updates.. Assigning to Alec or Matthew. Somehow I dont see Matthew in the list of assignees in Bridgs-Python repo.

**Comment by AlecGoncharow** [comment]
Found the problem, somehow an additional property decorator got added here https://github.com/BridgesUNCC/bridges-python/blob/0bd201d5fe66d43f90c5ae70b97f87b2dd17272f/bridges/data_src_dependent/earthquake_usgs.py#L72

it works on my end now.
