### ISSUE TITLE
rename USCities as City ?

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridges-python#97]

**Comment by esaule** [comment]
Since we seem to be using the current USCities object to represent both cities in the US and in the world. Should we really use USCities as the name?

Also, should we go singular ==> City ?

**Comment by esaule** [comment]
also, get_world_cities_data seem to hit localhost ATM

**Comment by krs-world** [comment]
Good idea.. will change to City

**Comment by krs-world** [comment]
Completed.

Changed USCities --> City,  changed test and tutorial for all 3 languages.
